DELETE  http://localhost:3003/api/blog/6530212782815707d550f269
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5la2kiLCJpZCI6IjY1MmZlMGIwZjJlOWM4MzI2OTRiZWQ2NiIsImlhdCI6MTY5NzY1NDUzN30.dmt-_JWDaM9Ao-Nhu1kkkhYz_5IGnlUKTPfrz60RDHU